---
- hosts: localhost
  tasks:
  - name: set hostname
    hostname:
      name: geext-workstation

  - name: remove unneeded packages
    become: true
    dnf:
      state: absent
      name: ["totem", "firefox"]

  - name: install rpmfusion
    become: true
    dnf:
      state: present
      name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-28.noarch.rpm

  - name: update system
    become: true
    dnf:
      state: latest
      name: '*'

  - name: install packages
    become: true
    dnf:
      state: present
      name: ["curl", "git", "gdb", "vim", "gcc", "gcc-c++", "python-psutil",
             "make", "meson", "gtk3-devel", "gstreamer1*devel", "podman",
             "buildah", "flatpak", "sshfs", "ruby", "ncurses-compat-libs",
             "cmake", "zsh", "powerline-fonts", "gtest-devel", "valgrind",
             "gnome-mpv", "keepassxc", "kcachegrind", "gradle"]

  - name: set zsh as a default shell
    become: true
    user:
      name: geext
      shell: /bin/zsh

  - name: configure with dconf
    dconf:
      key: "{{item.key}}"
      value: "{{item.value}}"
    loop:
      # interface
      - {key: "/org/gnome/desktop/interface/gtk-theme",
         value: "'Adwaita'"}
      - {key: "/org/gnome/desktop/wm/preferences/theme",
         value: "'Adwaita'"}
      - {key: "/org/gnome/desktop/interface/cursor-theme",
         value: "'Adwaita'"}
      - {key: "/org/gnome/desktop/interface/icon-theme",
         value: "'Adwaita'"}

      # fonts
      - {key: "/org/gnome/desktop/interface/font-name",
         value: "'Cantarell 10'"}
      - {key: "/org/gnome/desktop/wm/preferences/titlebar-font",
         value: "'Cantarell Bold 11'"}
      - {key: "/org/gnome/desktop/interface/document-font-name",
         value: "'Liberation Serif 12'"}
      - {key: "/org/gnome/desktop/interface/monospace-font-name",
         value: "'Monospace 10'"}
      - {key: "/org/gnome/settings-daemon/plugins/xsettings/hinting",
         value: "'full'"}
   
      # some preferences
      - {key: "/org/gnome/desktop/interface/show-battery-percentage",
         value: "false"}
      - {key: "/org/gnome/settings-daemon/plugins/color/night-light/enabled",
         value: "true"}
      - {key: "/org/gnome/settings-daemon/plugins/xsettings/antialiasing",
         value: "'rgba'"}
      - {key: "/org/gnome/shell/disable-user-extensions",
         value: "true"}
      - {key: "/org/gnome/system/location/enabled",
         value: "false"}
      - {key: "/org/gnome/desktop/privacy/report-technical-problems",
         value: "false"}

      # touchpad
      - {key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll",
         value: "false"}
      - {key: "/org/gnome/desktop/peripherals/touchpad/edge-scrolling-enabled",
         value: "true"}
      - {key: "/org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled",
         value: "false"}
      - {key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click",
         value: "true"}

  - name: configure git
    git_config:
      scope: global
      name: "{{item.key}}"
      value: "{{item.value}}"
    loop:
      - {key: "user.email",      value: "geext29@gmail.com"}
      - {key: "user.name",       value: "Denis Karpovskii"}
      - {key: "commit.gpgSign",  value: "true"}
      - {key: "gpg.program",     value: "gpg2"}
      - {key: "user.signingkey", value: "7F4413E312C92E4A"}

  - name: add flathub flatpak repo
    become: true
    flatpak_remote:
      state: present
      name: flathub
      flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

  - name: install flatpak apps
    become: true
    flatpak:
      state: present
      name: "{{item}}"
    loop:
    - com.google.AndroidStudio
    - com.spotify.Client

