---
- hosts: localhost
  tasks:
  - name: Add the RPM Fusion free repo
    become: true
    dnf:
      state: present
      name: '{{ rpmfusion_free_url }}'

  - name: Upgrade the system
    become: true
    dnf:
      state: latest
      name: '*'

  - name: Install system packages
    become: true
    dnf:
      state: present
      name: ['google-noto-sans-fonts', 'vim', 'gcc-c++', 'cmake', 'make',
             'meson', 'clang', 'llvm', 'flatpak', 'git', 'VirtualBox',
             'ffmpeg',

             # For building RPM packages
             'rpm-build', 'rpm-devel', 'rpmlint', 'coreutils', 'diffutils',
             'rpmdevtools',
             
             # for Qt development
             'qt5-devel']

# flatpak module is currently broken (probably due to the transition to python3)
#   - import_tasks: tasks/flatpak.yml
  - import_tasks: tasks/kde.yml
