---
- hosts: localhost
  tasks:
  - name: remove unneeded packages
    become: true
    dnf:
      state: absent
      name: ["dnfdragora", "firefox", "konqueror", "kmahjongg", "k3b",
             "krfb", "kpat", "kmines", "kolourpaint", "kruler",
             "akregator", "konversation", "krdc", "kmail", "knode",
             "falkon", "amarok", "kamoso", "dragon", "telepathy",
             "kamera", "kaddressbook", "akonadi-import-wizard",
	     "calligra-core", "kaccounts-integration", "kmousetool",
             "kmouth", "krusader", "kwrite", "kfind", "ark", "kmag",
             "korganizer", "mediawriter"]	 

  - name: update system
    become: true
    dnf:
      state: latest
      name: '*'

  - name: install packages
    become: true
    dnf:
      state: present
      name: ["curl", "git", "gdb", "vim", "gcc", "gcc-c++",
             "make", "meson", "flatpak", "sshfs", "ruby", "ncurses-compat-libs",
             "cmake", "zsh", "powerline-fonts", "gtest-devel",
             "ninja-build",
             "breeze-gtk",
             "google-noto-sans-fonts", "valgrind",
             "gradle"]
  
  - name: set zsh as a default shell
    become: true
    user:
      name: geext
      shell: /bin/zsh

  - name: configure git
    git_config:
      scope: global
      name: "{{item.key}}"
      value: "{{item.value}}"
    loop:
      - {key: "user.email",      value: "geext29@gmail.com"}
      - {key: "user.name",       value: "Denis Karpovskii"}
      - {key: "commit.gpgSign",  value: "true"}
      - {key: "gpg.program",     value: "gpg2"}
      - {key: "user.signingkey", value: "7F4413E312C92E4A"}

  - name: add flathub flatpak repo
    become: true
    flatpak_remote:
      state: present
      name: flathub
      flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

  - name: install flatpak apps
    become: true
    flatpak:
      state: present
      name: "{{item}}"
    loop:
    - com.google.AndroidStudio
    - com.spotify.Client
    - org.fedoraproject.MediaWriter
    - org.gimp.GIMP
    - org.libreoffice.LibreOffice
    - org.keepassxc.KeePassXC
    - com.uploadedlobster.peek

