---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: change hostname to lenovo-330
    become: true
    hostname:
      name: lenovo-330

  - name: Add the RPM Fusion free repo
    become: true
    dnf:
      state: present
      name: '{{ rpmfusion_free_url }}'

  - name: Remove unneeded packages
    become: true
    dnf:
      state: absent
      name: ['virtualbox-guest-additions', 'fedora-release-notes', 'abrt',
             'gnome-boxes', 'totem', 'rhythmbox', 'cheese', 'firefox',
             'libreoffice-core', 'gnome-weather']

  - name: Upgrade the system
    become: true
    dnf:
      state: latest
      name: '*'
  
  - name: Enable kitty-latest copr
    become: true
    command: "dnf copr enable -y gagbo/kitty-latest"
    args:
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:gagbo:kitty-latest.repo
  
  - name: Install system packages
    become: true
    dnf:
      state: present
      name: ['google-noto-sans-fonts',
             'neovim',
             'gcc-c++',
             'gdb',
             'cmake',
             'ninja-build',
             'make',
             'meson',
             'flatpak',
             'git',
             'podman',
             'buildah',
             'zram',
             'earlyoom',
             '{{ windscribe_rpm }}',
             '{{ google_chrome_rpm }}',

             # For building RPM packages
             'rpm-build',
             'rpm-devel',
             'rpmlint',
             'coreutils',
             'diffutils',
             'rpmdevtools',
             ]

  - name: Enable zram
    become: true
    systemd:
      enabled: true
      name: 'zram-swap.service'

  - name: Enable earlyoom
    become: true
    systemd:
      enabled: true
      name: 'earlyoom.service'

  - import_tasks: tasks/flatpak.yml
