---
- hosts: localhost
  tasks:
  - name: change hostname to lenovo-330
    become: true
    hostname:
      name: lenovo-330

  - name: Add the RPM Fusion free repo
    become: true
    dnf:
      state: present
      name: '{{ rpmfusion_free_url }}'

  - name: Remove unneeded packages
    become: true
    dnf:
      state: absent
      name: ['yelp', 'virtualbox-guest-additions']

  - name: Upgrade the system
    become: true
    dnf:
      state: latest
      name: '*'

  - name: Install system packages
    become: true
    dnf:
      state: present
      name: ['google-noto-sans-fonts',
             'vim',
             'gcc-c++',
             'gdb',
             'cmake',
             'ninja-build',
             'make',
             'flatpak',
             'git',
             'ffmpeg',
             'firefox',
             '{{ windscribe_rpm }}',

             # For building RPM packages
             'rpm-build',
             'rpm-devel',
             'rpmlint',
             'coreutils',
             'diffutils',
             'rpmdevtools',
             
             # for development
             'vulkan-loader-devel',
             'vulkan-validation-layers-devel',
             'vulkan-headers',
             'vulkan-tools',
             'glslang',
             'glfw-devel',
             'glm-devel',
             'mesa-libGL-devel'
             ]

# flatpak module is currently broken (probably due to the transition to python3)
#  - import_tasks: tasks/flatpak.yml
  - import_tasks: tasks/kde.yml
