---
- name: add flatpak repository
  become: true
  flatpak_remote:
    flatpakrepo_url: 'https://flathub.org/repo/flathub.flatpakrepo'
    name: 'flathub'
    state: present
    method: system
    
- name: install flatpaks
  become: true
  flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
  loop:
  - com.spotify.Client
  - org.videolan.VLC
  - org.keepassxc.KeePassXC
  - org.telegram.desktop
  - org.libreoffice.LibreOffice
  - org.qbittorrent.qBittorrent
  - org.gimp.GIMP
  - com.valvesoftware.Steam
  - org.gnome.eog
  - org.gnome.Evince
  - org.gnome.gedit
  - org.gnome.gitg
  - org.gnome.seahorse.Application
  - org.gnome.Fractal
  - org.gnome.Weather
  - org.gnome.Maps
  - org.gnome.Lollypop
  - org.gnome.Logs
  - org.gnome.Calculator
  - org.gnome.Calendar
  - org.gnome.Builder
  - org.gabmus.gfeeds
  - org.gnome.Boxes
  - org.gnome.DejaDup
  - info.febvre.Komikku
  - com.github.wwmm.pulseeffects
